-- Create the recipes table
create table recipes (
  id bigint generated by default as identity primary key,
  title text,
  author text,
  description text,
  ingredients text,
  instructions text,
  "imageUrl" text, 
  "chibiUrl" text,
  "servingSuggestions" text,
  "createdAt" timestamptz default now()
);
